sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t hsaad123/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true hsaad123/react-test npm test

after_success:
  - docker build -t hsaad123/multi-client ./client
  - docker build -t hsaad123/multi-nginx ./nginx
  - docker build -t hsaad123/multi-server ./server
  - docker build -t hsaad123/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push hsaad123/multi-client
  - docker push hsaad123/multi-nginx
  - docker push hsaad123/multi-server
  - docker push hsaad123/multi-worker

# deploy:
#   provider: elasticbeanstalk
#   region: us-west-1
#   app: multi-docker
#   env: MultiDocker-env
#   bucket-name: /
#   bucket-path: docker-multi
#   on:
#     branch: master
#   access_key_id: $AWS_ACCESS_KEY
#   secret_access_key: $AWS_SECRET_KEY